const API="/.netlify/functions",WA="2349021714170";
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=v=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v)||0);
function getCart(){return JSON.parse(localStorage.getItem("imma_cart")||"[]")}function saveCart(c){localStorage.setItem("imma_cart",JSON.stringify(c));updateCartCount()}function updateCartCount(){const n=getCart().reduce((a,x)=>a+x.quantity,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=n)}
function addToCart(p){const c=getCart(),x=c.find(i=>i.id===p.id);if(x)x.quantity++;else c.push({id:p.id,name:p.name,price:p.salePrice??p.price,image:p.image,quantity:1});saveCart(c);toast("Added to cart")}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));location.reload()}function changeQty(id,d){const c=getCart(),x=c.find(i=>i.id===id);if(!x)return;x.quantity=Math.max(1,x.quantity+d);saveCart(c);location.reload()}function clearCart(){saveCart([]);location.reload()}function cartTotal(){return getCart().reduce((a,x)=>a+(Number(x.price)||0)*x.quantity,0)}
async function getProducts(){try{const r=await fetch(`${API}/products`);if(!r.ok)throw Error();return await r.json()}catch(e){console.error(e);return[]}}
function productCard(p){return `<article class="glass rounded-3xl overflow-hidden"><a href="/product.html?id=${encodeURIComponent(p.id)}"><img src="${esc(p.image||"/imma-logo.png")}" alt="${esc(p.name)}" class="product-image" loading="lazy"></a><div class="p-4"><p class="text-xs text-cyan-300 mb-1">${esc(p.category||"")}</p><h3 class="font-semibold">${esc(p.name)}</h3><p class="font-bold mt-3">${money(p.salePrice??p.price)}</p><button class="glass-btn primary-btn w-full mt-4" data-add="${esc(p.id)}">ADD TO CART</button></div></article>`}
function bindAddButtons(ps){document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{const p=ps.find(x=>String(x.id)===String(b.dataset.add));if(p)addToCart(p)})}function waProduct(p){const m=`Hello IMMA GADGETS,\n\nI want to order:\n\nProduct: ${p.name}\nPrice: ${money(p.salePrice??p.price)}\n\nPlease confirm availability, payment and delivery details.`;open(`https://wa.me/${WA}?text=${encodeURIComponent(m)}`,"_blank")}function waCart(){const c=getCart();if(!c.length)return;const lines=c.map(x=>`• ${x.name} × ${x.quantity} — ${money(x.price*x.quantity)}`).join("\n");const m=`Hello IMMA GADGETS,\n\nI want to order:\n\n${lines}\n\nEstimated total: ${money(cartTotal())}\n\nPlease confirm availability, payment and delivery details.`;open(`https://wa.me/${WA}?text=${encodeURIComponent(m)}`,"_blank")}
function toast(t){let e=document.getElementById("toast");if(!e){e=document.createElement("div");e.id="toast";e.className="fixed bottom-5 left-1/2 -translate-x-1/2 glass pill px-5 py-3 z-[100]";document.body.appendChild(e)}e.textContent=t;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),1800)}document.addEventListener("DOMContentLoaded",updateCartCount);
